services:
  - type: web
    name: sustcomp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
